local ContextConfig = {}

ContextConfig.CONTEXT_MENU = {
    BARREL = "ContextMenu_BarrEx_Barrel",
    SYNCING = "ContextMenu_BarrEx_Syncing",
    OPEN_BARREL = "ContextMenu_BarrEx_OpenBarrel",
    INFO = "ContextMenu_BarrEx_Info",
    BARREL_INFO = "ContextMenu_BarrEx_BarrelInfo",
    REMOVE_THE_COVER = "ContextMenu_BarrEx_RemoveCover",
    POUR = "ContextMenu_BarrEx_Pour",
    POUR_ALL = "ContextMenu_BarrEx_PourAll",
    EXTRACT = "ContextMenu_BarrEx_Extract",
    INFO_PERCENT = "ContextMenu_BarrEx_InfoPercent",
    GROUPED_CONTAINER = "ContextMenu_BarrEx_GroupedContainer",
    POUR_CONTAINER = "ContextMenu_BarrEx_PourContainer",
    FALLBACK_FILL = "ContextMenu_BarrEx_FallbackFill",
    FALLBACK_FILL_ONE = "ContextMenu_BarrEx_FallbackFillOne",
    FALLBACK_FILL_ALL = "ContextMenu_BarrEx_FallbackFillAll",
    FALLBACK_TAKE_GAS = "ContextMenu_BarrEx_FallbackTakeGas",
    FALLBACK_DRINK = "ContextMenu_BarrEx_FallbackDrink",
    FALLBACK_WASH = "ContextMenu_BarrEx_FallbackWash",
    FALLBACK_YOURSELF = "ContextMenu_BarrEx_FallbackYourself",
    FALLBACK_WASH_ALL_CLOTHING = "ContextMenu_BarrEx_FallbackWashAllClothing",
    FALLBACK_EMPTY = "ContextMenu_BarrEx_FallbackEmpty",
    FALLBACK_INFO = "ContextMenu_BarrEx_FallbackInfo",
    ADMIN_DEBUG = "ContextMenu_BarrEx_AdminDebug",
    ADMIN_INSPECT = "ContextMenu_BarrEx_AdminInspect",
    ADMIN_REPAIR = "ContextMenu_BarrEx_AdminRepair",
    ADMIN_REVEAL_INIT = "ContextMenu_BarrEx_AdminRevealInit",
    ADMIN_EMPTY = "ContextMenu_BarrEx_AdminEmpty",
    ADMIN_SET_LIQUID = "ContextMenu_BarrEx_AdminSetLiquid",
    ADMIN_REROLL = "ContextMenu_BarrEx_AdminReroll",
    ADMIN_FILL_PERCENT = "ContextMenu_BarrEx_AdminFillPercent",
}

ContextConfig.TOOLTIP = {
    REQUIRED = "Tooltip_BarrEx_Required",
    ITEM_REQUIREMENT = "Tooltip_BarrEx_ItemRequirement",
    ONE_OF = "Tooltip_BarrEx_OneOf",
    BARREL_CONTENTS = "Tooltip_BarrEx_BarrelContents",
    LIQUID = "Tooltip_BarrEx_Liquid",
    AMOUNT = "Tooltip_BarrEx_Amount",
    WEIGHT = "Tooltip_BarrEx_Weight",
    TOO_FAR = "Tooltip_BarrEx_TooFar",
    REQUIRES_FUNNEL = "Tooltip_BarrEx_RequiresFunnel",
    REQUIRES_HOSE = "Tooltip_BarrEx_RequiresHose",
    MISSING_REQUIRED_TOOL = "Tooltip_BarrEx_MissingRequiredTool",
    BARREL_FULL = "Tooltip_BarrEx_BarrelFull",
    BARREL_EMPTY = "Tooltip_BarrEx_BarrelEmpty",
    BARREL_CLOSED = "Tooltip_BarrEx_BarrelClosed",
    INCOMPATIBLE_LIQUID = "Tooltip_BarrEx_IncompatibleLiquid",
    NO_COMPATIBLE_CONTAINER = "Tooltip_BarrEx_NoCompatibleContainer",
    BARREL_UNAVAILABLE = "Tooltip_BarrEx_BarrelUnavailable",
    NOT_DRINKABLE = "Tooltip_BarrEx_NotDrinkable",
    NOT_WASHABLE = "Tooltip_BarrEx_NotWashable",
    NOT_THIRSTY = "Tooltip_BarrEx_NotThirsty",
    NOTHING_TO_WASH = "Tooltip_BarrEx_NothingToWash",
    TAINTED_WATER = "Tooltip_BarrEx_TaintedWater",
    FILL_LEVEL = "Tooltip_BarrEx_FillLevel",
    TRANSFER_AMOUNT = "Tooltip_BarrEx_TransferAmount",
    CONTAINER_CAPACITY = "Tooltip_BarrEx_ContainerCapacity",
    FUEL_CAPACITY = "ContextMenu_FuelCapacity",
    STATUS = "Tooltip_BarrEx_Status",
    COMPATIBLE_CONTAINERS = "Tooltip_BarrEx_CompatibleContainers",
    NEED_CONTAINER_WITH_SPACE = "Tooltip_BarrEx_NeedContainerWithSpace",
    NEED_CONTAINER_WITH_LIQUID = "Tooltip_BarrEx_NeedContainerWithLiquid",
    NEED_MATCHING_LIQUID = "Tooltip_BarrEx_NeedMatchingLiquid",
    CURRENT_LIQUID = "Tooltip_BarrEx_CurrentLiquid",
    AVAILABLE = "Tooltip_BarrEx_Available",
    MISSING = "Tooltip_BarrEx_Missing",
    MORE_COMPATIBLE_CONTAINERS = "Tooltip_BarrEx_MoreCompatibleContainers",
    ITEM_RUBBER_HOSE = "Tooltip_BarrEx_Item_RubberHose",
}

ContextConfig.UI = {
    EMPTY = "UI_BarrEx_Empty",
    LIQUID_WATER = "UI_BarrEx_Liquid_WATER",
    LIQUID_TAINTED_WATER = "UI_BarrEx_Liquid_TAINTED_WATER",
    LIQUID_GASOLINE = "UI_BarrEx_Liquid_GASOLINE",
    LIQUID_BLEACH = "UI_BarrEx_Liquid_BLEACH",
}

return ContextConfig
